# Generated by Django 4.1.7 on 2023-10-13 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_comment_user_profile_comment_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
